MyPortfolio/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PORTFOLIO.urls', namespace="PORTFOLIO")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'PORTFOLIO'

urlpatterns = [
    path('', views.home, name = "home"),
    path('login/', views.login_view, name = "login"),
    path('user/', views.user_view, name = "user"),
    path('user/addproject/', views.add_project, name='addproject'),
    path('deleteproject/<int:id>/', views.delete_project, name='deleteproject'),
    path('updateproject/<int:id>/', views.update_project, name='updateproject'),
    path('logout/', views.custom_logout, name='logout'),
]

PORTFOLIO/models.py
from operator import mod
from unittest.util import _MAX_LENGTH
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe

class Product(models.Model):
    name = models.CharField(max_length = 100)
    price = models.FloatField()
    description = models.CharField(max_length = 100)


class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Graphic Design")
    description = models.TextField(default="desciption")
    image = models.ImageField(upload_to="category", default="category.jpg")
    
    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))
    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))
    def __str__(self):
        return self.title

class GraphicDesign(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    caption=models.CharField(max_length=100)
    image=models.ImageField(upload_to='img')
    def __str__(self):
        return self.caption

PORTFOLIO/forms.py
from django import forms
from .models import GraphicDesign
from django.forms import ModelForm


class ImageForm(forms.ModelForm):
    caption = forms.TextInput()
    category = forms.CheckboxSelectMultiple
    image = forms.ImageField()
    class Meta:
        model = GraphicDesign
        fields = ['image', 'caption', 'category']

class UIUXUpdateForm(forms.ModelForm):
    class Meta:
        model = GraphicDesign
        fields = ['image', 'caption']

PORTFOLIO/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from .models import Category, GraphicDesign
from .forms import UIUXUpdateForm
from .forms import ImageForm


def home(request):
    categories = Category.objects.prefetch_related('graphicdesign_set')

    if request.method == 'POST':
        email =request.POST['email']
        name = request.POST['email']
        message = request.POST['message']

        send_mail(name, message, email,[settings.EMAIL_HOST_USER], fail_silently=True)

    context = {
        'categories':categories,
    }
    return render(request, 'MyPortfolio/index.html', context)
@login_required
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_page = request.POST.get('next', '')  # Get the value of 'next' parameter
            if next_page:  # If 'next' parameter exists, redirect to it
                return redirect(next_page)
            else:  # Otherwise, redirect to a default page
                return redirect('PORTFOLIO:admin')  # Use URL name to redirect
        else:
            # Add a Bootstrap alert indicating wrong password
            messages.error(request, 'Wrong username or password. Please try again.')
            return redirect('PORTFOLIO:login')  # Redirect back to login page on failure
    return render(request, 'MyPortfolio/admin.html')
@login_required
def user_view(request):
    images = GraphicDesign.objects.all()
    categories = Category.objects.prefetch_related('graphicdesign_set')

    context = {
        'categories':categories,
        'images':images,
    }

    return render(request, 'MyPortfolio/admin.html', context)

@login_required
def add_project(request):
    if request.POST:
        form = ImageForm(request.POST, request.FILES)
        print(request.FILES)
        if form.is_valid():
            form.save()

    return render(request, 'MyPortfolio/addproject.html',context={'form' : ImageForm})

@login_required
def delete_project(request, id):
    project = GraphicDesign.objects.get(id=id)

    if request.method == "POST" and "confirm_delete" in request.POST:
        project.delete()
        return redirect('PORTFOLIO:user')

    return render(request, 'MyPortfolio/deleteproject.html', {'project': project})

@login_required
def update_project(request, id):
    image = GraphicDesign.objects.get(id=id)  # Fetch a single Uiux object based on id
    if request.method == "POST":
        form = UIUXUpdateForm(request.POST, request.FILES, instance=image)
        if form.is_valid():
            form.save()
            return redirect('PORTFOLIO:user')
    else:
        form = UIUXUpdateForm(instance=image)
    return render(request, 'MyPortfolio/updateproject.html', {'form': form, 'image': image})

@login_required
def custom_logout(request):
    logout(request)
    # Redirect to a desired page after logout
    return redirect('PORTFOLIO:home')  # Replace 'home' with the name of your desired URL pattern

PORTFOLIO/templates/MyPortfolio/addproject.html
{% extends 'partials/base-admin.html' %}
{% load static %}

{% block content %}





      <div class="content">
        <!-- Your main content here -->
        <div class="container">
          <form action="{% url 'PORTFOLIO:addproject' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            {{image}}
        </form>
            <hr>
        </div>
    </div>
    







  </div>


 {% endblock %}

PORTFOLIO/templates/MyPortfolio/admin.html
{% extends 'partials/base-admin.html' %}
{% load static %}

{% block content %}


<div class="row">
  {% for category in categories %}
  <div class="col-md-4 mb-4">
    <div class="card card-prj-design hvr-shrink">
      <img src="{{ category.image.url }}" class="card-img-top" alt="Project 1" style="height: 450px;">
      <div class="card-body">
        <h5 class="card-title">{{ category.title }}</h5>
        <p class="card-text">{{ category.description }}</p>
        <a class="btn btn-primary btn-full" data-bs-toggle="modal" data-bs-target="#MOD{{ category.cid }}">View Project</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% for category in categories %}
<div class="modal fade" id="MOD{{ category.cid }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" >
    <div class="modal-content modal-design">
      <div class="modal-header">
        <h1 class="modal-title fs-5 " id="exampleModalLabel">{{ category.title }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>


      <div class="container text-center">
        <div class="row row-cols-3">
          {% for graphic_design in category.graphicdesign_set.all %}
          <div class="modal-body">
            <div class="mb-4">
              <div class="card card-design hvr-float">
                <img src="{{ graphic_design.image.url }}" class="card-img-top" alt="" style="height: 425px; object-fit: cover;">
                <div class="card-body">
                  <h5 class="card-title">{{ graphic_design.caption }}</h5>
                  <a href="{% url 'PORTFOLIO:updateproject' graphic_design.id %}" type="button" class="btn btn-primary">
                    <i class="bi bi-pencil-fill"></i> Edit
                </a>
                <a href="{% url 'PORTFOLIO:deleteproject' graphic_design.id %}" type="button" class="btn btn-danger">
                    Delete Project
                </a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

      </div>
    </div>
  </div>

    </div>
  </div>
  {% endfor %}
          
  
{% endblock content%}










PORTFOLIO/templates/MyPortfolio/deleteproject.html
{% extends 'partials/base-admin.html' %}
{% load static %}

{% block content %}


        <div class="content">
          <!-- Main content -->
          <div class="container">
              <h1>Delete Confirmation</h1>
              <p>Are you sure you want to delete "{{ project.caption }}"?</p>
              <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <button class="btn btn-warning" type="submit" name="confirm_delete">Yes, Delete</button>
                  <a href="{% url 'PORTFOLIO:user' %}" type="button" class="btn btn-primary">Cancel</a>
              </form>
          </div>
      </div>
      
      </div>  

{% endblock %}
      
  













    <script src="/static/js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

PORTFOLIO/templates/MyPortfolio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Portfolio</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
    <link rel="stylesheet" href="{% static '/css/mediaqueries.css' %}" />
    <link rel="stylesheet" href="{% static '/css/aos.css' %}">
    <link rel="stylesheet" href="{% static '/css/hover-min.css' %}">
    <link rel="stylesheet" href="{% static '/css/hover.css' %}">
    <link rel="icon" href="{% static '/assets/person.png' %}">
  </head>
  <body>
    <nav id="desktop-nav" >
      <div class="logo">Rean Ariban Portfolio</div>
      <div>
        <ul class="nav-links">
          <li><a href="#about" class="hvr-shrink">About</a></li>
          <li><a href="#experience" class="hvr-shrink">Experience</a></li>
          <li><a href="#projects" class="hvr-shrink">Projects</a></li>
          <li><a href="" data-bs-toggle="modal" data-bs-target="#contact" class="hvr-shrink"> Contact</a></li>
          <li><a href="#" class="hvr-shrink" data-bs-toggle="modal" data-bs-target="#login" class="hvr-shrink">Login</a></li>
        </ul>
      </div>
    </nav>
    <nav id="hamburger-nav">
      <div class="logo">Rean Ariban Portfolio</div>
      <div class="hamburger-menu">
        <div class="hamburger-icon" onclick="toggleMenu()">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div class="menu-links">
          <li><a href="#about" onclick="toggleMenu()">About</a></li>
          <li><a href="#experience" onclick="toggleMenu()">Experience</a></li>
          <li><a href="#projects" onclick="toggleMenu()">Projects</a></li>
          <li><a href="#"data-bs-toggle="modal" data-bs-target="#contact"">Contact</a></li>
        </div>
      </div>
    </nav>
    <section id="profile">
      <div class="section__pic-container" data-aos="fade-up" data-aos-delay="100" data-aos-duration="2000">
        <img src="{% static '/assets/person.png' %}" alt="profile picture" class="hvr-grow" />
      </div>
      <div class="section__text" data-aos="fade-up" data-aos-delay="100" data-aos-duration="2000">
        <p class="section__text__p1">Hello, I'm</p>
        <h1 class="title">Rean Ariban</h1>
        <p class="section__text__p2">Graphic Designer</p>
        <div class="btn-container ">
          <a href="/assets/Rean-Aribans-Resume.pdf" download="downloaded_file_name"> 
            <button
            class="btn btn-color-2 hvr-grow" 
          >
            Download CV
          </button>  </a>
          <button class="btn btn-color-1 hvr-grow" data-bs-toggle="modal" data-bs-target="#contact">
            Contact Info
          </button>
        </div>
        <div id="socials-container">
          <img
            src="{% static '/assets/linkedin.png' %}"
            alt="My LinkedIn profile"
            class="icon"
            onclick="location.href='https://linkedin.com/'"
          />
          <img
            src="{% static '/assets/github.png' %}"
            alt="My Github profile"
            class="icon"
            onclick="location.href='https://github.com/ReanLuna'"
          />
        </div>
      </div>
    </section>
    <section id="about" data-aos="fade-up" data-aos-delay="100" data-aos-duration="2000">
      <p class="section__text__p1">Get To Know More</p>
      <h1 class="title">About Me</h1>
      <div class="section-container">
        <div class="section__pic-container">
          <img
            src="{% static '/assets/Profile pic.png' %}"
            alt="Profile picture"
            class="about-pic"
          />
        </div>
        <div class="about-details-container">
          <div class="about-containers">
            <div class="details-container hvr-float">
              <img
                src="{% static '/assets/experience.png' %}"
                alt="Experience icon"
                class="icon"
              />
              <h3>Experience</h3>
              <p>2+ years <br />Graphic Designer</p>
            </div>
            <div class="details-container hvr-float">
              <img
                src="{% static '/assets/education.png' %}"
                alt="Education icon"
                class="icon"
              />
              <h3>Education</h3>
              <p>Bachelor of science in information technology <br> student</p>
            </div>
          </div>
          <div class="text-container">
            <p>
              Hello! I'm Renievan F. Ariban, a graduating student from Western Mindanao State University with a Bachelor of Science in Information Technology. With a strong foundation in graphic design and proficiency in Adobe Photoshop and Illustrator, I'm passionate about crafting compelling visuals that resonate with audiences. Through internships and freelance projects, I've honed my skills and am now eager to apply my expertise to make impactful contributions in the creative industry. Let's connect and create something amazing together!
            </p>
          </div>
        </div>
      </div>
      <img
        src="{% static '/assets/arrow.png' %}"
        alt="Arrow icon"
        class="icon arrow"
        onclick="location.href='./#experience'"
      />
    </section>
    <section id="experience" data-aos="fade-up" data-aos-delay="100" data-aos-duration="2000">
      <p class="section__text__p1">Explore My</p>
      <h1 class="title">Experience</h1>
      <div class="experience-details-container">
        <div class="about-containers">
          <div class="details-container hvr-float">
            <h2 class="experience-sub-title ">Frontend Development</h2>
            <div class="article-container">
              <article>
                <img
                  src="{% static '/assets/checkmark.png' %}"
                  alt="Experience icon"
                  class="icon"
                />
                <div>
                  <h3>HTML</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="{% static '/assets/checkmark.png' %}"
                  alt="Experience icon"
                  class="icon"
                />
                <div>
                  <h3>CSS</h3>
                  <p>Experienced</p>
                </div>
              </article>
            </div>
          </div>
          <div class="details-container hvr-float">
            <h2 class="experience-sub-title">Graphic Designer</h2>
            <div class="article-container">
              <article>
                <img
                  src="{% static '/assets/checkmark.png' %}"
                  alt="Experience icon"
                  class="icon"
                />
                <div>
                  <h3>Adobe Photoshop</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="{% static '/assets/checkmark.png' %}"
                  alt="Experience icon"
                  class="icon"
                />
                <div>
                  <h3>Adobe Illustrator</h3>
                  <p>Experienced</p>
                </div>
              </article>
            </div>
          </div>
        </div>
      </div>
      <br>
      <img
      src="{% static '/assets/arrow.png' %}"
      alt="Arrow icon"
      class="icon arrow"
      onclick="location.href='./#projects'"
    />
    </section>

    <section id="projects" data-aos="fade-up" data-aos-delay="100" data-aos-duration="2000">
      <div class="container prj-cont ">
        <h1 class="mt-5 mb-4">My Projects</h1>
        <div class="row">




          <!-- Project 1 -->
          {% for category in categories %}
          <div class="col-md-4 mb-4">
            <div class="card card-prj-design hvr-shrink">
              <img src="{{ category.image.url }}" class="card-img-top" alt="Project 1" style="height: 450px;">
              <div class="card-body">
                <h5 class="card-title">{{ category.title }}</h5>
                <p class="card-text">{{ category.desciption }}</p>
                <a class="btn btn-primary btn-full" data-bs-toggle="modal" data-bs-target="#MOD{{ category.cid }}">View Project</a>
              </div>
            </div>
          </div>
          {% endfor %}

          
        </div>
      </div>
    </section>







<!-- Modal -->
{% for category in categories %}
<div class="modal fade" id="MOD{{ category.cid }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" >
    <div class="modal-content modal-design">
      <div class="modal-header">
        <h1 class="modal-title fs-5 " id="exampleModalLabel">{{ category.title }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>


      <div class="container text-center">
        <div class="row row-cols-3">
          {% for graphic_design in category.graphicdesign_set.all %}
          <div class="modal-body">
            <div class="mb-4">
              <div class="card card-design hvr-float">
                <img src="{{ graphic_design.image.url }}" class="card-img-top" alt="" style="height: 425px; object-fit: cover;">
                <div class="card-body">
                  <h5 class="card-title">{{ graphic_design.caption }}</h5>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

      </div>
    </div>
  </div>

    </div>
  </div>
  {% endfor %}


<!-- Modal  Contact-->
<div class="modal fade " id="contact" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog ">
    <div class="modal-content modal-xl contact-body">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">


        <div class="modal-body">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="recipient-name" class="col-form-label" for="name">Name:</label>
              <input class="form-control"  type="name" id="name" name="name" required>
              <label for="email">Email:</label>
              <input class="form-control" type="email" id="email" name="email" required><br>
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Message:</label>
              <textarea class="form-control" id="message-text"  id="message" name="message"></textarea>
              <div class="modal-footer contact-footer">
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </div>
          </form>
        </div>

      </div>

    </div>
  </div>
</div>

<div class="modal fade " id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog ">
    <div class="modal-content modal-xl contact-body">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">


        <div class="container-login">
          <div class="row justify-content-center">
            <div class="col-md-6 login-container">
              <img src="{% static '/assets/person.png' %}" alt="#" class="imglogin">
              <form method="post" action="{% url 'PORTFOLIO:login' %}">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" class="form-control" name="username" id="id_username" placeholder="Enter Username"required>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" name="password" id="id_password" placeholder="Enter Password"required>
                </div>
                <br>
                <input type="hidden" name="next" value="{% url 'PORTFOLIO:user' %}">
                <div class="buttonlogin">
                <button type="submit" class="btn btn-primary btn-block btn-login">Login</button>
              </div>
              </form>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


   <footer class="bg-light text-center text-lg-start mt-auto">
    <div class="container p-4 cnt-footer">
      <p>&copy; 2024 My Projects. All rights reserved.</p>
    </div>
  </footer>
  
    <script src="{% static '/js/script.js' %}"></script>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/js/aos.js' %}"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

PORTFOLIO/templates/MyPortfolio/updateproject.html
{% extends 'partials/base-admin.html' %}
{% load static %}

{% block content %}


        <div class="content">
          <!-- Main content -->
          <div class="container">
              <h1>Update Project: {{ image.caption }}</h1>
              <img src="{{ image.image.url }}" class="card-img-top" alt="" style="width: 325px; height: 425px; object-fit: cover;">
              <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-lg btn-success">Submit</button>
              </form>
          </div>
      </div>
      
      </div>
      
  





{% endblock %}

PORTFOLIO/templates/partials/base-admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rean Ariban</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css" />
    <link rel="stylesheet" href="/static/css/mediaqueries.css" />
    <link rel="stylesheet" href="/static/css/aos.css">
    <link rel="stylesheet" href="/static/css/hover-min.css">
    <link rel="stylesheet" href="/static/css/hover.css">
  </head>
  <body>

    <div class="sidebar" data-aos="fade-right" data-aos-delay="100" data-aos-duration="2000"">
        <img src="/static/assets/person.png" alt="">
        <a href="{% url 'PORTFOLIO:user' %}" class="hvr-float">Home</a>
        <a href="{% url 'PORTFOLIO:addproject' %}"class="hvr-float">Add Project</a>
        <a href="{% url 'PORTFOLIO:logout' %}" class="hvr-float">Log Out</a>
      </div>












      <div style="margin-left: 250px; padding: 20px;">



        {% block content %}

            
        {% endblock %}
      


        




    <script src="/static/js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>